server:
  port: 5000

localeTag: en-UK

telegram-bot:
  botUsername: ${USERNAME}
  botToken: ${TOKEN}
  botPath: ${WEB_HOOK_PATH}

calendar:
  id1: ${CALENDAR_ID_ARTIFICIAL_COVERING}
  id2: ${CALENDAR_ID_FOOTBALL_FIELD}
  id3: ${CALENDAR_ID_TABLE_TENNIS}

  spring:
    jpa:
      hibernate:
        ddl-auto: update
    datasource:
      url: ${SQL_URL}
      username: ${SQL_USERNAME}
      password: ${SQL_PASSWORD}
      driver-class-name: org.postgresql.Driver

      redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
        database: 0
        lettuce:
          pool:
            max-active: 8
            max-idle: 8

        cache:
          type: redis
          redis:
            cache-null-values: false